COMMON_ARTICLE_POOL: list[str] = [
    "Africa",
    "Antarctica",
    "Asia",
    "Europe",
    "North America",
    "South America",
    "Australia",
    "United States",
    "Canada",
    "Mexico",
    "Brazil",
    "Argentina",
    "Chile",
    "Peru",
    "Colombia",
    "United Kingdom",
    "France",
    "Germany",
    "Italy",
    "Spain",
    "Portugal",
    "Netherlands",
    "Belgium",
    "Sweden",
    "Norway",
    "Finland",
    "Denmark",
    "Poland",
    "Ukraine",
    "Greece",
    "Turkey",
    "Russia",
    "China",
    "Japan",
    "South Korea",
    "India",
    "Pakistan",
    "Indonesia",
    "Philippines",
    "Thailand",
    "Vietnam",
    "Singapore",
    "Malaysia",
    "Saudi Arabia",
    "Egypt",
    "South Africa",
    "Nigeria",
    "Kenya",
    "Morocco",
    "Israel",
    "Iran",
    "Iraq",
    "New Zealand",
    "Rome",
    "London",
    "Paris",
    "Berlin",
    "Madrid",
    "Lisbon",
    "Athens",
    "Istanbul",
    "Moscow",
    "Kyiv",
    "Beijing",
    "Tokyo",
    "Seoul",
    "Delhi",
    "Mumbai",
    "Bangkok",
    "Jakarta",
    "Cairo",
    "Johannesburg",
    "New York City",
    "Los Angeles",
    "Chicago",
    "Houston",
    "San Francisco",
    "Seattle",
    "Las Vegas",
    "Washington, D.C.",
    "Boston",
    "Miami",
    "Toronto",
    "Montreal",
    "Vancouver",
    "Sydney",
    "Melbourne",
    "Rio de Janeiro",
    "Sao Paulo",
    "Amazon rainforest",
    "Nile",
    "Mississippi River",
    "Yangtze",
    "Mount Everest",
    "Himalayas",
    "Sahara",
    "Grand Canyon",
    "Great Barrier Reef",
    "Arctic Ocean",
    "Pacific Ocean",
    "Atlantic Ocean",
    "Indian Ocean",
    "Mediterranean Sea",
    "Black Sea",
    "Solar System",
    "Sun",
    "Moon",
    "Mercury (planet)",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
    "Milky Way",
    "Galaxy",
    "Black hole",
    "Big Bang",
    "NASA",
    "International Space Station",
    "Apollo 11",
    "SpaceX",
    "Physics",
    "Chemistry",
    "Biology",
    "Astronomy",
    "Geology",
    "Mathematics",
    "Algebra",
    "Geometry",
    "Calculus",
    "Pi",
    "Prime number",
    "Periodic table",
    "Atom",
    "Molecule",
    "DNA",
    "Cell (biology)",
    "Evolution",
    "Natural selection",
    "Genetics",
    "Human body",
    "Human brain",
    "Heart",
    "Lung",
    "Immune system",
    "Bacteria",
    "Virus",
    "Computer",
    "Internet",
    "World Wide Web",
    "Website",
    "Search engine",
    "Google",
    "YouTube",
    "Wikipedia",
    "Artificial intelligence",
    "Machine learning",
    "Programming language",
    "Python (programming language)",
    "JavaScript",
    "C++",
    "Linux",
    "Microsoft Windows",
    "Apple Inc.",
    "Microsoft",
    "Amazon (company)",
    "Meta Platforms",
    "Tesla, Inc.",
    "Nintendo",
    "Sony",
    "PlayStation",
    "Xbox",
    "Steam (service)",
    "Video game",
    "Arcade game",
    "Esports",
    "World War I",
    "World War II",
    "Cold War",
    "Ancient Egypt",
    "Ancient Greece",
    "Roman Empire",
    "Middle Ages",
    "Renaissance",
    "Industrial Revolution",
    "French Revolution",
    "American Revolution",
    "United States Declaration of Independence",
    "United States Constitution",
    "Civil rights movement",
    "Great Depression",
    "Moon landing",
    "Berlin Wall",
    "United Nations",
    "European Union",
    "NATO",
    "Democracy",
    "Republic",
    "Monarchy",
    "Capitalism",
    "Socialism",
    "Communism",
    "Philosophy",
    "Psychology",
    "Sociology",
    "Economics",
    "Money",
    "Inflation",
    "Stock market",
    "Cryptocurrency",
    "Bitcoin",
    "Dollar",
    "Music",
    "Rock music",
    "Pop music",
    "Hip hop music",
    "Jazz",
    "Classical music",
    "Blues",
    "Country music",
    "Piano",
    "Guitar",
    "Violin",
    "Drum kit",
    "Singing",
    "The Beatles",
    "Michael Jackson",
    "Taylor Swift",
    "Beyonce",
    "Eminem",
    "Mozart",
    "Beethoven",
    "Film",
    "Cinema",
    "Animation",
    "Hollywood",
    "Academy Awards",
    "The Godfather",
    "Star Wars",
    "The Lord of the Rings",
    "Harry Potter",
    "Marvel Cinematic Universe",
    "Batman",
    "Spider-Man",
    "Superman",
    "Sherlock Holmes",
    "Literature",
    "Novel",
    "Poetry",
    "Shakespeare",
    "William Shakespeare",
    "Homer",
    "Dante Alighieri",
    "J. R. R. Tolkien",
    "George Orwell",
    "Science fiction",
    "Fantasy",
    "Mystery fiction",
    "Sports",
    "Football",
    "Basketball",
    "Baseball",
    "Soccer",
    "Tennis",
    "Golf",
    "Cricket",
    "Rugby",
    "Olympic Games",
    "FIFA World Cup",
    "Super Bowl",
    "National Basketball Association",
    "Major League Baseball",
    "National Football League",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Michael Jordan",
    "LeBron James",
    "Serena Williams",
    "Tiger Woods",
    "Usain Bolt",
    "Chess",
    "Poker",
    "Board game",
    "Monopoly (game)",
    "Scrabble",
    "Dungeons & Dragons",
    "Minecraft",
    "Tetris",
    "Pac-Man",
    "Super Mario",
    "The Legend of Zelda",
    "Pokémon",
    "Halo (franchise)",
    "Dark Souls",
    "Sekiro: Shadows Die Twice",
    "Elden Ring",
    "FromSoftware",
    "Fortnite",
    "League of Legends",
    "Valorant",
    "Overwatch",
    "Roblox",
    "Food",
    "Pizza",
    "Hamburger",
    "Pasta",
    "Rice",
    "Bread",
    "Chocolate",
    "Coffee",
    "Tea",
    "Sushi",
    "Taco",
    "Ice cream",
    "Medicine",
    "Vaccine",
    "Antibiotic",
    "Cancer",
    "Diabetes",
    "Heart disease",
    "Pandemic",
    "COVID-19",
    "Architecture",
    "Eiffel Tower",
    "Statue of Liberty",
    "Great Wall of China",
    "Colosseum",
    "Pyramids of Giza",
    "Taj Mahal",
    "Golden Gate Bridge",
    "Transportation",
    "Car",
    "Train",
    "Airplane",
    "Bicycle",
    "Ship",
    "Subway",
    "Religion",
    "Christianity",
    "Islam",
    "Hinduism",
    "Buddhism",
    "Judaism",
    "Mythology",
    "Greek mythology",
    "Norse mythology",
    "Art",
    "Painting",
    "Sculpture",
    "Museum",
    "Louvre",
    "Mona Lisa",
    "Vincent van Gogh",
    "Pablo Picasso",
    "Leonardo da Vinci",
    "Albert Einstein",
    "Isaac Newton",
    "Marie Curie",
    "Charles Darwin",
    "Nikola Tesla",
    "Galileo Galilei",
    "Stephen Hawking",
    "Alan Turing",
    "Ada Lovelace",
    "George Washington",
    "Abraham Lincoln",
    "Theodore Roosevelt",
    "Franklin D. Roosevelt",
    "John F. Kennedy",
    "Martin Luther King Jr.",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Winston Churchill",
    "Napoleon",
    "Julius Caesar",
    "Cleopatra",
    "Joan of Arc",
    "Genghis Khan",
    "Alexander the Great",
    "United States",
    "California",
    "Texas",
    "Florida",
    "New York (state)",
    "Pennsylvania",
    "Ohio",
    "Georgia (U.S. state)",
    "North Carolina",
    "Michigan",
    "New Jersey",
    "Virginia",
    "Washington (state)",
    "Arizona",
    "Massachusetts",
    "Tennessee",
    "Indiana",
    "Missouri",
    "Maryland",
    "Wisconsin",
    "Colorado",
    "Minnesota",
    "South Carolina",
    "Alabama",
    "Louisiana",
    "Kentucky",
    "Oregon",
    "Oklahoma",
    "Connecticut",
    "Utah",
    "Iowa",
    "Nevada",
    "Arkansas",
    "Mississippi",
    "Kansas",
    "New Mexico",
    "Nebraska",
    "Idaho",
    "West Virginia",
    "Hawaii",
    "New Hampshire",
    "Maine",
    "Montana",
    "Rhode Island",
    "Delaware",
    "South Dakota",
    "North Dakota",
    "Alaska",
    "Vermont",
    "Wyoming",
]
