ENTERTAINMENT_ARTICLE_POOL: list[str] = [
    "Minecraft",
    "Fortnite",
    "Roblox",
    "League of Legends",
    "Dota 2",
    "Valorant",
    "Overwatch",
    "Counter-Strike",
    "Apex Legends",
    "Rocket League",
    "Grand Theft Auto V",
    "The Elder Scrolls V: Skyrim",
    "The Witcher 3: Wild Hunt",
    "Dark Souls",
    "Elden Ring",
    "Sekiro: Shadows Die Twice",
    "Bloodborne",
    "Hades (video game)",
    "Stardew Valley",
    "Terraria",
    "Celeste (video game)",
    "Hollow Knight",
    "Undertale",
    "Cuphead",
    "Dead Cells",
    "Slay the Spire",
    "Balatro",
    "Portal (video game)",
    "Portal 2",
    "Half-Life 2",
    "Left 4 Dead 2",
    "Team Fortress 2",
    "BioShock",
    "Mass Effect 2",
    "Red Dead Redemption 2",
    "God of War (2018 video game)",
    "The Last of Us",
    "The Last of Us Part II",
    "Uncharted 4: A Thief's End",
    "Ghost of Tsushima",
    "Horizon Zero Dawn",
    "Marvel's Spider-Man",
    "Super Mario Bros.",
    "Super Mario 64",
    "Super Mario Odyssey",
    "Mario Kart 8",
    "The Legend of Zelda",
    "The Legend of Zelda: Ocarina of Time",
    "The Legend of Zelda: Breath of the Wild",
    "The Legend of Zelda: Tears of the Kingdom",
    "Pokemon Red and Blue",
    "Pokemon Gold and Silver",
    "Pokemon Scarlet and Violet",
    "Metroid Prime",
    "Animal Crossing: New Horizons",
    "Splatoon 3",
    "Super Smash Bros. Ultimate",
    "Tetris",
    "Pac-Man",
    "Space Invaders",
    "Street Fighter II",
    "Mortal Kombat",
    "Tekken 7",
    "Final Fantasy VII",
    "Final Fantasy XIV",
    "Persona 5",
    "Kingdom Hearts",
    "NieR: Automata",
    "Metal Gear Solid 3: Snake Eater",
    "Resident Evil 4",
    "Silent Hill 2",
    "Halo: Combat Evolved",
    "Halo 3",
    "Call of Duty 4: Modern Warfare",
    "Call of Duty: Warzone",
    "Battlefield 1",
    "Doom (1993 video game)",
    "Doom Eternal",
    "Quake (video game)",
    "Destiny 2",
    "Warframe",
    "Among Us",
    "Fall Guys",
    "Genshin Impact",
    "World of Warcraft",
    "RuneScape",
    "Diablo II",
    "Diablo IV",
    "StarCraft",
    "StarCraft II: Wings of Liberty",
    "Age of Empires II",
    "Civilization VI",
    "The Sims 4",
    "Cities: Skylines",
    "XCOM 2",
    "FIFA 23",
    "EA Sports FC 24",
    "NBA 2K24",
    "Madden NFL 24",
    "Gran Turismo 7",
    "Forza Horizon 5",
    "Need for Speed",
    "Assassin's Creed II",
    "Assassin's Creed Valhalla",
    "Cyberpunk 2077",
    "Baldur's Gate 3",
    "Disco Elysium",
    "Outer Wilds",
    "No Man's Sky",
    "Subnautica",
    "Sea of Thieves",
    "Phasmophobia",
    "Lethal Company",
    "Clash of Clans",
    "Candy Crush Saga",
    "Pokemon Go",
    "Angry Birds",
    "Chess",
    "Checkers",
    "Go (game)",
    "Backgammon",
    "Scrabble",
    "Monopoly (game)",
    "Risk (game)",
    "Clue (board game)",
    "The Game of Life",
    "Battleship (game)",
    "Connect Four",
    "Jenga",
    "Twister (game)",
    "Uno (card game)",
    "Poker",
    "Mahjong",
    "Catan",
    "Ticket to Ride (board game)",
    "Carcassonne (board game)",
    "Pandemic (board game)",
    "7 Wonders (board game)",
    "Dominion (card game)",
    "Terraforming Mars (board game)",
    "Wingspan (board game)",
    "Azul (board game)",
    "Gloomhaven",
    "Root (board game)",
    "Codenames (board game)",
    "Exploding Kittens",
    "Magic: The Gathering",
    "Yu-Gi-Oh!",
    "Pokemon Trading Card Game",
    "Dungeons & Dragons",
    "Warhammer 40,000",
    "Jaws (film)",
    "Star Wars (film)",
    "The Empire Strikes Back",
    "Return of the Jedi",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Harry Potter and the Philosopher's Stone (film)",
    "The Godfather",
    "The Dark Knight",
    "The Shawshank Redemption",
    "Pulp Fiction",
    "Forrest Gump",
    "Fight Club",
    "Inception",
    "Interstellar (film)",
    "The Matrix",
    "Gladiator (2000 film)",
    "Titanic (1997 film)",
    "Avatar (2009 film)",
    "Avatar: The Way of Water",
    "Top Gun: Maverick",
    "Jurassic Park (film)",
    "Back to the Future",
    "Ghostbusters",
    "Home Alone",
    "E.T. the Extra-Terrestrial",
    "The Lion King",
    "Toy Story",
    "Toy Story 3",
    "Finding Nemo",
    "The Incredibles",
    "Inside Out (2015 film)",
    "Coco (2017 film)",
    "Shrek",
    "Frozen (2013 film)",
    "Moana (2016 film)",
    "Spider-Man: Into the Spider-Verse",
    "Spider-Man: Across the Spider-Verse",
    "Iron Man (2008 film)",
    "The Avengers (2012 film)",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Guardians of the Galaxy (film)",
    "Black Panther (film)",
    "The Super Mario Bros. Movie",
    "Mad Max: Fury Road",
    "Whiplash (2014 film)",
    "La La Land (film)",
    "The Social Network",
    "Oppenheimer (film)",
    "Barbie (film)",
    "Dune (2021 film)",
    "Dune: Part Two",
    "The Simpsons",
    "Family Guy",
    "South Park",
    "SpongeBob SquarePants",
    "Avatar: The Last Airbender",
    "The Legend of Korra",
    "Rick and Morty",
    "Adventure Time",
    "Regular Show",
    "Gravity Falls",
    "Arcane (TV series)",
    "Bluey (2018 TV series)",
    "Game of Thrones",
    "House of the Dragon",
    "Breaking Bad",
    "Better Call Saul",
    "The Sopranos",
    "The Wire",
    "Friends",
    "Seinfeld",
    "The Office (American TV series)",
    "Parks and Recreation",
    "Brooklyn Nine-Nine",
    "How I Met Your Mother",
    "The Big Bang Theory",
    "Modern Family",
    "Ted Lasso",
    "Stranger Things",
    "Wednesday (TV series)",
    "The Walking Dead (TV series)",
    "Lost (2004 TV series)",
    "The Last of Us (TV series)",
    "The Mandalorian",
    "Andor (TV series)",
    "Loki (TV series)",
    "WandaVision",
    "Daredevil (TV series)",
    "Sherlock (TV series)",
    "Doctor Who",
    "Black Mirror",
    "The Boys (2019 TV series)",
    "Invincible (TV series)",
    "Peaky Blinders (TV series)",
    "Narcos",
    "True Detective",
    "Dexter (TV series)",
    "House (TV series)",
    "Grey's Anatomy",
    "The Crown (TV series)",
    "Chernobyl (miniseries)",
    "The Queen's Gambit (miniseries)",
    "The Bear (TV series)",
    "Succession (TV series)",
    "Euphoria (American TV series)",
    "Cobra Kai",
    "Squid Game",
    "One Piece (2023 TV series)",
    "The Witcher (TV series)",
    "The Umbrella Academy (TV series)",
    "Prison Break",
    "Vikings (2013 TV series)",
]

EXTRA_CATEGORY_ARTICLES: list[str] = [
    "Naruto",
    "One Piece",
    "Dragon Ball",
    "Attack on Titan",
    "Death Note",
    "Demon Slayer: Kimetsu no Yaiba",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Fullmetal Alchemist",
    "Bleach (TV series)",
    "Tokyo Ghoul",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "Hunter x Hunter",
    "Sailor Moon",
    "World Cup",
    "UEFA Champions League",
    "Premier League",
    "National Basketball Association",
    "National Football League",
    "Major League Baseball",
    "Olympic Games",
    "Summer Olympic Games",
    "Winter Olympic Games",
    "FIFA World Cup",
    "Wimbledon Championships",
    "Super Bowl",
    "Formula One",
    "Tour de France",
    "Cricket World Cup",
    "American football",
    "Basketball",
    "Baseball",
    "Tennis",
    "Soccer",
    "Milky Way",
    "Solar System",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Moon",
    "Black hole",
    "Galaxy",
    "Astronomy",
    "Space exploration",
    "Apollo 11",
    "International Space Station",
    "Hubble Space Telescope",
    "James Webb Space Telescope",
    "Physics",
    "Biology",
    "Mathematics",
    "Google",
    "YouTube",
    "Wikipedia",
    "Internet",
    "World Wide Web",
    "Web browser",
    "Mozilla Firefox",
    "Google Chrome",
    "Microsoft Edge",
    "OpenAI",
    "Artificial intelligence",
    "Virtual reality",
    "Smartphone",
    "iPhone",
    "Android (operating system)",
    "PlayStation",
    "Xbox",
    "Nintendo",
    "Steam (service)",
    "Ancient Egypt",
    "Ancient Greece",
    "Roman Empire",
    "Middle Ages",
    "Renaissance",
    "Industrial Revolution",
    "World War I",
    "World War II",
    "Cold War",
    "Silk Road",
    "Black Death",
    "Moon landing",
    "History of writing",
    "History of the internet",
    "Great Wall of China",
    "Machu Picchu",
    "Eiffel Tower",
    "Colosseum",
    "Statue of Liberty",
    "Taj Mahal",
    "Mount Everest",
    "Amazon rainforest",
    "Sahara",
    "Pacific Ocean",
    "Atlantic Ocean",
    "Nile",
    "Tokyo",
    "New York City",
    "Paris",
    "London",
    "Pizza",
    "Sushi",
    "Hamburger",
    "Taco",
    "Pasta",
    "Ramen",
    "Chocolate",
    "Coffee",
    "Tea",
    "Ice cream",
    "Sandwich",
    "French cuisine",
    "Italian cuisine",
    "Japanese cuisine",
    "Mexican cuisine",
    "Indian cuisine",
    "Greek mythology",
    "Norse mythology",
    "Mythology",
    "Folklore",
    "Zeus",
    "Athena",
    "Poseidon",
    "Odin",
    "Thor",
    "Loki",
    "Dragon",
    "Vampire",
    "Werewolf",
    "Mermaid",
    "Mona Lisa",
    "The Starry Night",
    "The Scream",
    "Vincent van Gogh",
    "Pablo Picasso",
    "Leonardo da Vinci",
    "William Shakespeare",
    "Hamlet",
    "Macbeth",
    "Romeo and Juliet",
    "Harry Potter",
    "The Hobbit",
    "The Lord of the Rings",
    "Pride and Prejudice",
    "To Kill a Mockingbird",
]

ENTERTAINMENT_ARTICLE_POOL.extend(EXTRA_CATEGORY_ARTICLES)
