ENTERTAINMENT_ARTICLE_POOL: list[str] = [
    "Minecraft",
    "Fortnite",
    "Roblox",
    "League of Legends",
    "Dota 2",
    "Valorant",
    "Overwatch",
    "Counter-Strike",
    "Apex Legends",
    "Rocket League",
    "Grand Theft Auto V",
    "The Elder Scrolls V: Skyrim",
    "The Witcher 3: Wild Hunt",
    "Dark Souls",
    "Elden Ring",
    "Sekiro: Shadows Die Twice",
    "Bloodborne",
    "Hades (video game)",
    "Stardew Valley",
    "Terraria",
    "Celeste (video game)",
    "Hollow Knight",
    "Undertale",
    "Cuphead",
    "Dead Cells",
    "Slay the Spire",
    "Balatro",
    "Portal (video game)",
    "Portal 2",
    "Half-Life 2",
    "Left 4 Dead 2",
    "Team Fortress 2",
    "BioShock",
    "Mass Effect 2",
    "Red Dead Redemption 2",
    "God of War (2018 video game)",
    "The Last of Us",
    "The Last of Us Part II",
    "Uncharted 4: A Thief's End",
    "Ghost of Tsushima",
    "Horizon Zero Dawn",
    "Marvel's Spider-Man",
    "Super Mario Bros.",
    "Super Mario 64",
    "Super Mario Odyssey",
    "Mario Kart 8",
    "The Legend of Zelda",
    "The Legend of Zelda: Ocarina of Time",
    "The Legend of Zelda: Breath of the Wild",
    "The Legend of Zelda: Tears of the Kingdom",
    "Pokémon Red and Blue",
    "Pokémon Gold and Silver",
    "Pokémon Scarlet and Violet",
    "Metroid Prime",
    "Animal Crossing: New Horizons",
    "Splatoon 3",
    "Super Smash Bros. Ultimate",
    "Tetris",
    "Pac-Man",
    "Space Invaders",
    "Street Fighter II",
    "Mortal Kombat",
    "Tekken 7",
    "Final Fantasy VII",
    "Final Fantasy XIV",
    "Persona 5",
    "Kingdom Hearts",
    "NieR: Automata",
    "Metal Gear Solid 3: Snake Eater",
    "Resident Evil 4",
    "Silent Hill 2",
    "Halo: Combat Evolved",
    "Halo 3",
    "Call of Duty 4: Modern Warfare",
    "Call of Duty: Warzone",
    "Battlefield 1",
    "Doom (1993 video game)",
    "Doom Eternal",
    "Quake (video game)",
    "Destiny 2",
    "Warframe",
    "Among Us",
    "Fall Guys",
    "Genshin Impact",
    "World of Warcraft",
    "RuneScape",
    "Diablo II",
    "Diablo IV",
    "StarCraft",
    "StarCraft II: Wings of Liberty",
    "Age of Empires II",
    "Civilization VI",
    "The Sims 4",
    "Cities: Skylines",
    "XCOM 2",
    "FIFA 23",
    "EA Sports FC 24",
    "NBA 2K24",
    "Madden NFL 24",
    "Gran Turismo 7",
    "Forza Horizon 5",
    "Need for Speed",
    "Assassin's Creed II",
    "Assassin's Creed Valhalla",
    "Cyberpunk 2077",
    "Baldur's Gate 3",
    "Disco Elysium",
    "Outer Wilds",
    "No Man's Sky",
    "Subnautica",
    "Sea of Thieves",
    "Phasmophobia",
    "Lethal Company",
    "Clash of Clans",
    "Candy Crush Saga",
    "Pokémon Go",
    "Angry Birds",
    "Chess",
    "Checkers",
    "Go (game)",
    "Backgammon",
    "Scrabble",
    "Monopoly (game)",
    "Risk (game)",
    "Cluedo",
    "The Game of Life",
    "Battleship (game)",
    "Connect Four",
    "Jenga",
    "Twister (game)",
    "Uno (card game)",
    "Poker",
    "Mahjong",
    "Catan",
    "Ticket to Ride (board game)",
    "Carcassonne (board game)",
    "Pandemic (board game)",
    "7 Wonders (board game)",
    "Dominion (card game)",
    "Terraforming Mars (board game)",
    "Wingspan (board game)",
    "Azul (board game)",
    "Gloomhaven",
    "Root (board game)",
    "Codenames (board game)",
    "Exploding Kittens",
    "Magic: The Gathering",
    "Yu-Gi-Oh!",
    "Pokémon Trading Card Game",
    "Dungeons & Dragons",
    "Warhammer 40,000",
    "Jaws (film)",
    "Star Wars (film)",
    "The Empire Strikes Back",
    "Return of the Jedi",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Harry Potter and the Philosopher's Stone (film)",
    "The Godfather",
    "The Dark Knight",
    "The Shawshank Redemption",
    "Pulp Fiction",
    "Forrest Gump",
    "Fight Club",
    "Inception",
    "Interstellar (film)",
    "The Matrix",
    "Gladiator (2000 film)",
    "Titanic (1997 film)",
    "Avatar (2009 film)",
    "Avatar: The Way of Water",
    "Top Gun: Maverick",
    "Jurassic Park (film)",
    "Back to the Future",
    "Ghostbusters",
    "Home Alone",
    "E.T. the Extra-Terrestrial",
    "The Lion King",
    "Toy Story",
    "Toy Story 3",
    "Finding Nemo",
    "The Incredibles",
    "Inside Out (2015 film)",
    "Coco (2017 film)",
    "Shrek",
    "Frozen (2013 film)",
    "Moana (2016 film)",
    "Spider-Man: Into the Spider-Verse",
    "Spider-Man: Across the Spider-Verse",
    "Iron Man (2008 film)",
    "The Avengers (2012 film)",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Guardians of the Galaxy (film)",
    "Black Panther (film)",
    "The Super Mario Bros. Movie",
    "Mad Max: Fury Road",
    "Whiplash (2014 film)",
    "La La Land",
    "The Social Network",
    "Oppenheimer (film)",
    "Barbie (film)",
    "Dune (2021 film)",
    "Dune: Part Two",
    "The Simpsons",
    "Family Guy",
    "South Park",
    "SpongeBob SquarePants",
    "Avatar: The Last Airbender",
    "The Legend of Korra",
    "Rick and Morty",
    "Adventure Time",
    "Regular Show",
    "Gravity Falls",
    "Arcane (TV series)",
    "Bluey (2018 TV series)",
    "Game of Thrones",
    "House of the Dragon",
    "Breaking Bad",
    "Better Call Saul",
    "The Sopranos",
    "The Wire",
    "Friends",
    "Seinfeld",
    "The Office (American TV series)",
    "Parks and Recreation",
    "Brooklyn Nine-Nine",
    "How I Met Your Mother",
    "The Big Bang Theory",
    "Modern Family",
    "Ted Lasso",
    "Stranger Things",
    "Wednesday (TV series)",
    "The Walking Dead (TV series)",
    "Lost (2004 TV series)",
    "The Last of Us (TV series)",
    "The Mandalorian",
    "Andor (TV series)",
    "Loki (TV series)",
    "WandaVision",
    "Daredevil (TV series)",
    "Sherlock (TV series)",
    "Doctor Who",
    "Black Mirror",
    "The Boys (2019 TV series)",
    "Invincible (TV series)",
    "Peaky Blinders (TV series)",
    "Narcos",
    "True Detective",
    "Dexter (TV series)",
    "House (TV series)",
    "Grey's Anatomy",
    "The Crown (TV series)",
    "Chernobyl (miniseries)",
    "The Queen's Gambit (miniseries)",
    "The Bear (TV series)",
    "Succession (TV series)",
    "Euphoria (American TV series)",
    "Cobra Kai",
    "Squid Game",
    "One Piece (2023 TV series)",
    "The Witcher (TV series)",
    "The Umbrella Academy (TV series)",
    "Prison Break",
    "Vikings (2013 TV series)",
]

EXTRA_CATEGORY_ARTICLES: list[str] = [
    "Naruto",
    "One Piece",
    "Dragon Ball",
    "Attack on Titan",
    "Death Note",
    "Demon Slayer: Kimetsu no Yaiba",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Fullmetal Alchemist",
    "Bleach (TV series)",
    "Tokyo Ghoul",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "Hunter x Hunter",
    "Sailor Moon",
    "World Cup",
    "UEFA Champions League",
    "Premier League",
    "National Basketball Association",
    "National Football League",
    "Major League Baseball",
    "Olympic Games",
    "Summer Olympic Games",
    "Winter Olympic Games",
    "FIFA World Cup",
    "Wimbledon Championships",
    "Super Bowl",
    "Formula One",
    "Tour de France",
    "Cricket World Cup",
    "American football",
    "Basketball",
    "Baseball",
    "Tennis",
    "Soccer",
    "Milky Way",
    "Solar System",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Moon",
    "Black hole",
    "Galaxy",
    "Astronomy",
    "Space exploration",
    "Apollo 11",
    "International Space Station",
    "Hubble Space Telescope",
    "James Webb Space Telescope",
    "Physics",
    "Biology",
    "Mathematics",
    "Google",
    "YouTube",
    "Wikipedia",
    "Internet",
    "World Wide Web",
    "Web browser",
    "Mozilla Firefox",
    "Google Chrome",
    "Microsoft Edge",
    "OpenAI",
    "Artificial intelligence",
    "Virtual reality",
    "Smartphone",
    "iPhone",
    "Android (operating system)",
    "PlayStation",
    "Xbox",
    "Nintendo",
    "Steam (service)",
    "Ancient Egypt",
    "Ancient Greece",
    "Roman Empire",
    "Middle Ages",
    "Renaissance",
    "Industrial Revolution",
    "World War I",
    "World War II",
    "Cold War",
    "Silk Road",
    "Black Death",
    "Moon landing",
    "History of writing",
    "History of the internet",
    "Great Wall of China",
    "Machu Picchu",
    "Eiffel Tower",
    "Colosseum",
    "Statue of Liberty",
    "Taj Mahal",
    "Mount Everest",
    "Amazon rainforest",
    "Sahara",
    "Pacific Ocean",
    "Atlantic Ocean",
    "Nile",
    "Tokyo",
    "New York City",
    "Paris",
    "London",
    "Pizza",
    "Sushi",
    "Hamburger",
    "Taco",
    "Pasta",
    "Ramen",
    "Chocolate",
    "Coffee",
    "Tea",
    "Ice cream",
    "Sandwich",
    "French cuisine",
    "Italian cuisine",
    "Japanese cuisine",
    "Mexican cuisine",
    "Indian cuisine",
    "Greek mythology",
    "Norse mythology",
    "Mythology",
    "Folklore",
    "Zeus",
    "Athena",
    "Poseidon",
    "Odin",
    "Thor",
    "Loki",
    "Dragon",
    "Vampire",
    "Werewolf",
    "Mermaid",
    "Mona Lisa",
    "The Starry Night",
    "The Scream",
    "Vincent van Gogh",
    "Pablo Picasso",
    "Leonardo da Vinci",
    "William Shakespeare",
    "Hamlet",
    "Macbeth",
    "Romeo and Juliet",
    "Harry Potter",
    "The Hobbit",
    "The Lord of the Rings",
    "Pride and Prejudice",
    "To Kill a Mockingbird",
]

ENTERTAINMENT_ARTICLE_POOL.extend(EXTRA_CATEGORY_ARTICLES)

MORE_EXTRA_ARTICLES: list[str] = [
    "The Legend of Zelda: Majora's Mask",
    "The Legend of Zelda: A Link to the Past",
    "The Legend of Zelda: Wind Waker",
    "The Legend of Zelda: Twilight Princess",
    "The Legend of Zelda: Skyward Sword",
    "Super Mario World",
    "Super Mario Galaxy",
    "Super Mario Galaxy 2",
    "Super Mario Sunshine",
    "Mario Party",
    "Mario Party Superstars",
    "Mario Kart Wii",
    "Mario Kart 64",
    "Paper Mario",
    "Luigi's Mansion",
    "Luigi's Mansion 3",
    "Pokémon Yellow",
    "Pokémon Ruby and Sapphire",
    "Pokémon Diamond and Pearl",
    "Pokémon Black and White",
    "Pokémon Sun and Moon",
    "Pokémon Legends: Arceus",
    "Metroid",
    "Super Metroid",
    "Metroid Dread",
    "Kirby Super Star",
    "Kirby and the Forgotten Land",
    "Donkey Kong Country",
    "Donkey Kong Country 2",
    "F-Zero",
    "Fire Emblem: Three Houses",
    "Advance Wars",
    "EarthBound",
    "Mother 3",
    "Chrono Trigger",
    "Chrono Cross",
    "Final Fantasy VI",
    "Final Fantasy IX",
    "Final Fantasy X",
    "Dragon Quest XI",
    "Kingdom Hearts II",
    "Persona 4",
    "Persona 3 Reload",
    "Shin Megami Tensei",
    "NieR Replicant",
    "Octopath Traveler",
    "Bravely Default",
    "Monster Hunter: World",
    "Monster Hunter Rise",
    "Resident Evil 2",
    "Resident Evil Village",
    "Silent Hill",
    "Dead Space (2008 video game)",
    "Alan Wake",
    "Control (video game)",
    "The Elder Scrolls III: Morrowind",
    "The Elder Scrolls IV: Oblivion",
    "Fallout: New Vegas",
    "Fallout 4",
    "The Witcher 2: Assassins of Kings",
    "Cyberpunk: Edgerunners",
    "Dark Souls II",
    "Dark Souls III",
    "Demon's Souls",
    "Armored Core VI: Fires of Rubicon",
    "Hollow Knight: Silksong",
    "Celeste 64: Fragments of the Mountain",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "Dead by Daylight",
    "Risk of Rain 2",
    "Spelunky",
    "Spelunky 2",
    "The Binding of Isaac: Rebirth",
    "Enter the Gungeon",
    "Inscryption",
    "FTL: Faster Than Light",
    "Into the Breach",
    "Papers, Please",
    "Return of the Obra Dinn",
    "Factorio",
    "Satisfactory",
    "RimWorld",
    "Kerbal Space Program",
    "Noita",
    "Valheim",
    "Palworld",
    "Vampire Survivors",
    "Brotato",
    "Peglin",
    "Balatro",
    "Slay the Spire 2",
    "Portal",
    "Half-Life",
    "Half-Life: Alyx",
    "Left 4 Dead",
    "Counter-Strike 2",
    "Team Fortress Classic",
    "Quake II",
    "Doom II",
    "Wolfenstein 3D",
    "StarCraft: Brood War",
    "Warcraft III: Reign of Chaos",
    "Age of Mythology",
    "Command & Conquer",
    "Civilization V",
    "Sid Meier's Civilization IV",
    "Heroes of Might and Magic III",
    "Disco Elysium",
    "Outer Wilds",
    "Subnautica: Below Zero",
    "XCOM: Enemy Unknown",
    "The Sims",
    "The Sims 2",
    "The Sims 3",
    "Cities: Skylines II",
    "SimCity 4",
    "Euro Truck Simulator 2",
    "Gran Turismo 4",
    "Forza Motorsport",
    "Need for Speed: Most Wanted",
    "Burnout 3: Takedown",
    "Tony Hawk's Pro Skater 2",
    "SSX 3",
    "Wii Sports",
    "Wii Sports Resort",
    "Clubhouse Games: 51 Worldwide Classics",
    "Backgammon",
    "Connect Four",
    "Battleship (game)",
    "Cluedo",
    "Sorry! (game)",
    "Yahtzee",
    "Bingo (American version)",
    "Uno (card game)",
    "Magic: The Gathering",
    "Pokémon Trading Card Game",
    "Yu-Gi-Oh! Trading Card Game",
    "Exploding Kittens",
    "Dominion (card game)",
    "Pandemic (board game)",
    "Pandemic Legacy: Season 1",
    "7 Wonders (board game)",
    "Wingspan (board game)",
    "Azul (board game)",
    "Splendor (game)",
    "Codenames (board game)",
    "Root (board game)",
    "Terraforming Mars",
    "Betrayal at House on the Hill",
    "Munchkin (card game)",
    "Settlers of Catan",
    "Tabletop game",
    "Role-playing game",
    "Strategy game",
    "Cooperative board game",
    "Card game",
    "Board game",
    "Discord",
    "Twitch (service)",
    "Reddit",
    "Steam Deck",
    "Nintendo Switch",
    "PlayStation 2",
    "PlayStation 5",
    "Xbox 360",
    "Xbox Series X and Series S",
    "GameCube",
    "Wii",
    "Wii U",
    "Nintendo 64",
    "Super Nintendo Entertainment System",
    "Game Boy",
    "Game Boy Advance",
    "Nintendo DS",
    "PlayStation Portable",
    "PlayStation Vita",
    "Sega Genesis",
    "Dreamcast",
    "Atari 2600",
    "Arcade game",
    "Home video game console",
    "Handheld game console",
    "PC gaming",
    "Esports",
    "Speedrun",
    "Video game developer",
    "Video game publisher",
    "Indie game",
    "Game engine",
    "Unity (game engine)",
    "Unreal Engine 5",
    "Source (game engine)",
    "Godot (game engine)",
    "Open source software",
    "Linux",
    "Windows 11",
    "macOS",
    "iOS",
    "Android",
    "Artificial general intelligence",
    "Machine learning",
    "Cloud gaming",
    "Virtual reality headset",
]

ENTERTAINMENT_ARTICLE_POOL.extend(MORE_EXTRA_ARTICLES)

MASSIVE_EXTRA_ARTICLES: list[str] = [
    "Animal Crossing",
    "Animal Crossing: Wild World",
    "Animal Crossing: New Leaf",
    "Banjo-Kazooie",
    "Banjo-Tooie",
    "Bastion (video game)",
    "Bayonetta",
    "Bayonetta 2",
    "Borderlands 2",
    "Borderlands 3",
    "Brawl Stars",
    "Castlevania",
    "Castlevania: Symphony of the Night",
    "Crash Bandicoot",
    "Crash Bandicoot 4: It's About Time",
    "Darkest Dungeon",
    "Deus Ex",
    "Deus Ex: Human Revolution",
    "Dishonored",
    "Dishonored 2",
    "Dragon Age: Origins",
    "Dragon Age: Inquisition",
    "Fable II",
    "Far Cry 3",
    "Far Cry 5",
    "For Honor",
    "Gears of War",
    "Gears 5",
    "GoldenEye 007 (1997 video game)",
    "Guilty Gear Strive",
    "Hitman (2016 video game)",
    "Hitman 3",
    "Hotline Miami",
    "Hotline Miami 2: Wrong Number",
    "Journey (2012 video game)",
    "Katamari Damacy",
    "Kingdom Come: Deliverance",
    "The Stanley Parable",
    "LittleBigPlanet",
    "LittleBigPlanet 2",
    "Mafia II",
    "Marvel vs. Capcom 2",
    "Mega Man 2",
    "Mega Man X",
    "Mirror's Edge",
    "Mortal Shell",
    "Ninja Gaiden",
    "Nioh",
    "Nioh 2",
    "Okami",
    "Omori",
    "Onimusha",
    "Overcooked",
    "Overcooked 2",
    "Paladins (video game)",
    "Path of Exile",
    "Plants vs. Zombies",
    "Prey (2017 video game)",
    "Prince of Persia: The Sands of Time",
    "Psychonauts",
    "Psychonauts 2",
    "Rayman Legends",
    "Rayman Origins",
    "Returnal",
    "Shovel Knight",
    "Skate 3",
    "Skullgirls",
    "Sly Cooper and the Thievius Raccoonus",
    "Sonic Adventure 2",
    "Sonic Mania",
    "Soulcalibur II",
    "Star Fox 64",
    "Star Wars Jedi: Fallen Order",
    "Star Wars Jedi: Survivor",
    "Sunset Overdrive",
    "The Talos Principle",
    "The World Ends with You",
    "Titanfall 2",
    "Tom Clancy's Rainbow Six Siege",
    "Torchlight II",
    "Transistor (video game)",
    "Warcraft II: Tides of Darkness",
    "Wasteland 3",
    "Xenoblade Chronicles",
    "Xenoblade Chronicles 2",
    "Yakuza 0",
    "Yakuza: Like a Dragon",
    "Zero Escape: Virtue's Last Reward",
    "A Game of Thrones (board game)",
    "Agricola (board game)",
    "Arkham Horror",
    "Bang! (card game)",
    "Blood Rage (board game)",
    "Brass: Birmingham",
    "Camel Up",
    "Captain Sonar",
    "Cascadia (board game)",
    "Citadels (card game)",
    "Concordia (board game)",
    "Cosmic Encounter",
    "Coup (card game)",
    "Deck-building game",
    "Dice game",
    "Dixit (card game)",
    "Eldritch Horror",
    "Forbidden Island (board game)",
    "Forbidden Desert",
    "Gloomhaven",
    "Hive (game)",
    "King of Tokyo",
    "Love Letter (card game)",
    "Ludo",
    "Mastermind (board game)",
    "Meeple",
    "Poker",
    "Race for the Galaxy",
    "Santorini (game)",
    "Scythe (board game)",
    "Sequence (game)",
    "Skull (card game)",
    "Small World (board game)",
    "The Crew: The Quest for Planet Nine",
    "The Game of Life",
    "Trivial Pursuit",
    "Twilight Imperium",
    "Word game",
    "Zombicide",
    "A Quiet Place (film)",
    "Alien (film)",
    "Aliens (film)",
    "Arrival (film)",
    "Back to the Future",
    "Blade Runner",
    "Blade Runner 2049",
    "Catch Me If You Can",
    "Coraline (film)",
    "Doctor Strange (2016 film)",
    "Donnie Darko",
    "E.T. the Extra-Terrestrial",
    "Edge of Tomorrow",
    "Everything Everywhere All at Once",
    "Finding Nemo",
    "Finding Dory",
    "Ghostbusters",
    "Her (2013 film)",
    "How to Train Your Dragon (film)",
    "Howl's Moving Castle (film)",
    "John Wick",
    "John Wick: Chapter 4",
    "Kill Bill: Volume 1",
    "Knives Out",
    "Madagascar (2005 film)",
    "Mean Girls",
    "Mission: Impossible – Fallout",
    "Monsters, Inc.",
    "Night at the Museum",
    "No Country for Old Men",
    "Parasite (film)",
    "Pulp Fiction",
    "Ratatouille (film)",
    "Ready Player One (film)",
    "School of Rock",
    "Shrek",
    "Shrek 2",
    "Spider-Man 2",
    "Spirited Away",
    "The Batman (film)",
    "The Grand Budapest Hotel",
    "The Hunger Games (film)",
    "The Incredibles",
    "The Lego Movie",
    "The Lion King",
    "The Martian (film)",
    "The Prestige (film)",
    "The Truman Show",
    "Top Gun: Maverick",
    "Up (2009 film)",
    "Wall-E",
    "Wreck-It Ralph",
    "X-Men: Days of Future Past",
    "Arrested Development",
    "BoJack Horseman",
    "Buffy the Vampire Slayer",
    "Community (TV series)",
    "Doctor Who (2005 TV series)",
    "Futurama",
    "Gilmore Girls",
    "Glee (TV series)",
    "Hannibal (TV series)",
    "Heartstopper",
    "It's Always Sunny in Philadelphia",
    "Jane the Virgin",
    "Killing Eve",
    "Lost in Space (2018 TV series)",
    "Lucifer (TV series)",
    "Malcolm in the Middle",
    "Mr. Robot",
    "MythBusters",
    "Only Murders in the Building",
    "Ozark (TV series)",
    "Psych (TV series)",
    "Scrubs (TV series)",
    "Sex Education (TV series)",
    "Suits (American TV series)",
    "Supernatural (American TV series)",
    "The Good Place",
    "The Haunting of Hill House",
    "The IT Crowd",
    "The Leftovers (TV series)",
    "The Owl House",
    "The X-Files",
    "Twin Peaks",
    "What We Do in the Shadows (TV series)",
    "X-Men '97",
    "Assassination Classroom",
    "Berserk",
    "Black Clover",
    "Chainsaw Man",
    "Code Geass",
    "Dandadan",
    "Dr. Stone",
    "Fairy Tail",
    "Frieren",
    "Gintama",
    "Haikyu!!",
    "Hellsing",
    "Inuyasha",
    "JoJo's Bizarre Adventure",
    "Kaguya-sama: Love Is War",
    "Mob Psycho 100",
    "Monster (manga)",
    "Mushoku Tensei",
    "One Punch Man",
    "Parasyte",
    "Pokémon (TV series)",
    "Re:Zero",
    "Samurai Champloo",
    "Solo Leveling",
    "Spy × Family",
    "Steins;Gate",
    "The Apothecary Diaries",
    "Tokyo Revengers",
    "Trigun",
    "Vinland Saga",
    "Volleyball",
    "Ice hockey",
    "National Hockey League",
    "College football",
    "College basketball",
    "Association football",
    "Rugby union",
    "Rugby World Cup",
    "Boxing",
    "Mixed martial arts",
    "Ultimate Fighting Championship",
    "Professional wrestling",
    "Table tennis",
    "Badminton",
    "Athletics (sport)",
    "Track and field",
    "Marathon",
    "Swimming (sport)",
    "Gymnastics",
    "Skateboarding",
    "Snowboarding",
    "Skiing",
    "Surfing",
    "World Series",
    "Stanley Cup",
    "UEFA European Championship",
    "Copa América",
    "Albert Einstein",
    "Isaac Newton",
    "Nikola Tesla",
    "Marie Curie",
    "Charles Darwin",
    "Stephen Hawking",
    "Galileo Galilei",
    "Quantum mechanics",
    "General relativity",
    "Theory of relativity",
    "Cell (biology)",
    "Photosynthesis",
    "Natural selection",
    "Evolution",
    "Climate change",
    "Oceanography",
    "Ecology",
    "Paleontology",
    "Dinosaur",
    "Tyrannosaurus",
    "Triceratops",
    "SpaceX",
    "NASA",
    "Apollo program",
    "Venus",
    "Mercury (planet)",
    "Neptune",
    "Uranus",
    "Pluto",
    "Exoplanet",
    "Computer science",
    "JavaScript",
    "Python (programming language)",
    "Java (programming language)",
    "Git",
    "GitHub",
    "Web development",
    "Frontend and backend",
    "Search engine",
    "Streaming media",
    "Netflix",
    "Spotify",
    "Email",
    "Wireless network",
    "Bluetooth",
    "USB",
    "Laptop",
    "Desktop computer",
    "Microprocessor",
    "Graphics processing unit",
    "Semiconductor",
    "Cybersecurity",
    "Deep learning",
    "Ancient Rome",
    "Byzantine Empire",
    "Ottoman Empire",
    "Mongol Empire",
    "French Revolution",
    "American Revolution",
    "Victorian era",
    "Stone Age",
    "Bronze Age",
    "Iron Age",
    "Age of Discovery",
    "Space Race",
    "Great Depression",
    "Roaring Twenties",
    "Feudalism",
    "Magna Carta",
    "Berlin Wall",
    "Norman conquest",
    "Crusades",
    "Printing press",
    "RMS Titanic",
    "Steam engine",
    "Asia",
    "Europe",
    "Africa",
    "North America",
    "South America",
    "Australia",
    "Antarctica",
    "Japan",
    "United States",
    "Canada",
    "Mexico",
    "Brazil",
    "United Kingdom",
    "Germany",
    "Italy",
    "Spain",
    "China",
    "South Korea",
    "India",
    "Egypt",
    "Mount Fuji",
    "Grand Canyon",
    "Niagara Falls",
    "Yellowstone National Park",
    "Mount Kilimanjaro",
    "Great Barrier Reef",
    "Mediterranean Sea",
    "Arctic Ocean",
    "Pacific Ring of Fire",
    "Sicily",
    "Hawaii",
    "Bread",
    "Cake",
    "Cookie",
    "Dumpling",
    "Burrito",
    "Nachos",
    "Lasagna",
    "Spaghetti",
    "Curry",
    "Fried rice",
    "Noodle",
    "Soup",
    "Salad",
    "Steak",
    "Pancake",
    "Waffle",
    "French fries",
    "Milkshake",
    "Cheesecake",
    "Sashimi",
    "Tempura",
    "Falafel",
    "Croissant",
    "Espresso",
    "Soda",
    "Breakfast",
    "Lunch",
    "Dinner",
    "The Odyssey",
    "The Iliad",
    "The Divine Comedy",
    "Don Quixote",
    "Frankenstein",
    "Dracula",
    "Moby-Dick",
    "The Great Gatsby",
    "1984 (novel)",
    "Animal Farm",
    "The Catcher in the Rye",
    "Jane Austen",
    "Mark Twain",
    "Charles Dickens",
    "Edgar Allan Poe",
    "J. R. R. Tolkien",
    "George Orwell",
    "Fyodor Dostoevsky",
    "Claude Monet",
    "Michelangelo",
    "Rembrandt",
    "Salvador Dalí",
    "The Last Supper (Leonardo)",
    "Girl with a Pearl Earring",
    "Roman mythology",
    "Egyptian mythology",
    "Japanese mythology",
    "Celtic mythology",
    "Hades",
    "Ares",
    "Hercules",
    "Achilles",
    "Perseus",
    "Medusa",
    "Pegasus",
    "Minotaur",
    "Cyclops",
    "Phoenix (mythology)",
    "Kraken",
    "Basilisk",
    "Fairy",
    "Ghost",
]

ENTERTAINMENT_ARTICLE_POOL.extend(MASSIVE_EXTRA_ARTICLES)



